apiVersion: v1
kind: Namespace
metadata:
    name: ssm
---
apiVersion: v1
kind: Secret
metadata:
    name: ssmcloud-secret
    namespace: ssmagent
stringData:
    mongodb_server: 127.0.0.1
    mongodb_db: ssm
    mongodb_user: ssm
    mongodb_pass: "#SSMPa$£"
type: Opaque

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: ssmcloud-data-pvc
    namespace: ssm
    annotations:
        volume.alpha.kubernetes.io/storage-class: "generic"
    labels:
        app.kubernetes.io/name: ssmcloud
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ssmcloud
    namespace: ssm
spec:
    selector:
        matchLabels:
            app: ssmcloud
    replicas: 2
    template:
        metadata:
            labels:
                app: ssmcloud
        spec:
            volumes:
                - name: ssmdata
                  persistentVolumeClaim:
                      claimName: ssmcloud-data-pvc
            containers:
                - env:
                      - name: MONGODB_SERVER
                        valueFrom:
                            secretKeyRef:
                                key: mongodb_server
                                name: ssmcloud-secret
                      - name: MONGODB_DB
                        valueFrom:
                            secretKeyRef:
                                key: mongodb_db
                                name: ssmcloud-secret
                      - name: MONGODB_USER
                        valueFrom:
                            secretKeyRef:
                                key: mongodb_user
                                name: ssmcloud-secret
                      - name: MONGODB_PASS
                        valueFrom:
                            secretKeyRef:
                                key: mongodb_pass
                                name: ssmcloud-secret
                - name: ssmcloud
                  image: mrhid6/ssmcloud:latest
                  ports:
                      - containerPort: 3000
                  volumeMounts:
                      - mountPath: "/SSM/Cloud/data"
                        name: ssmdata
---
apiVersion: v1
kind: Service
metadata:
    name: ssmcloud-svc
    namespace: ssm
spec:
    type: LoadBalancer
    selector:
        app: ssmcloud
    ports:
        - port: 3000
          targetPort: 3000
