apiVersion: apps/v1
kind: Deployment
metadata:
    name: ssmcloud
spec:
    selector:
        matchLabels:
            app: ssmcloud
    replicas: 1
    template:
        metadata:
            labels:
                app: ssmcloud
        spec:
            containers:
                - name: ssmcloud
                  image: mrhid6/ssmcloud:latest
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: ssmcloud-svc
spec:
    type: LoadBalancer
    selector:
        app: ssmcloud
    ports:
        - port: 3000
          targetPort: 3000
