kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: ssmcloud-data-pvc
    annotations:
        volume.alpha.kubernetes.io/storage-class: "generic"
    labels:
        app.kubernetes.io/name: ssmcloud
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ssmcloud
spec:
    selector:
        matchLabels:
            app: ssmcloud
    replicas: 2
    template:
        metadata:
            labels:
                app: ssmcloud
        spec:
            volumes:
                - name: ssmdata
                  persistentVolumeClaim:
                      claimName: ssmcloud-data-pvc
            containers:
                - env:
                      - name: SSM_BACKEND_URL
                        value: https://api-ssmcloud.hostxtra.co.uk
                  name: ssmcloud
                  image: mrhid6/ssmcloud:latest
                  ports:
                      - containerPort: 3000
                  volumeMounts:
                      - mountPath: "/SSM/Cloud/data"
                        name: ssmdata
---
apiVersion: v1
kind: Service
metadata:
    name: ssmcloud-svc
spec:
    type: LoadBalancer
    selector:
        app: ssmcloud
    ports:
        - port: 3000
          targetPort: 3000
